version: "3"
services:
  postgres:
    container_name: postgres-cloud-saves-db-test
    image: postgres:15
    ports:
      - "5666:5432"
    volumes:
      - ./docker-volumes/test/pgdata:/data/postgres
    environment:
      POSTGRES_USER: cloud-saves-backend
      POSTGRES_PASSWORD: 12121212
      POSTGRES_DB: cloud-saves-db-test

  pgadmin:
    container_name: cloud-saves-pgadmin-test
    links:
      - postgres:postgres
    image: dpage/pgadmin4:6.20
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12121212

  redis:
    container_name: redis-cloud-saves-test
    image: redis:7.0.2
    ports:
      - "6379:6379"
    volumes:
      - ./docker-volumes/test/redis:/data/redis

  minio:
    image: minio/minio:RELEASE.2024-03-15T01-07-19Z.fips
    volumes:
      - ./docker-volumes/test/s3/data1-1:/data1
      - ./docker-volumes/test/s3/data1-2:/data2
    ports:
      - "10000:9000"
      - "10001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio/data{1...2} --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
