version: "3"
services:
  cloud-saves-backend:
    build:
      context: ../deployments/app-local
    volumes:
      - ../internal:/internal
      - ../cmd:/cmd
      - ../docs:/docs
      - ../.go/pkg:/go/pkg
      - ../.go-cache:/go-cache
      - ../go.mod:/go.mod
      - ../go.sum:/go.sum
      - ../.env.docker:/.env
    working_dir: /
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - minio

  postgres:
    container_name: postgres-cloud-saves-db
    image: postgres:15
    ports:
      - "5444:5432"
    volumes:
      - ./docker-volumes/dev/pgdata:/data/postgres
    environment:
      POSTGRES_USER: cloud-saves-backend
      POSTGRES_PASSWORD: 12121212
      POSTGRES_DB: cloud-saves-db

  pgadmin:
    container_name: cloud-saves-pgadmin
    links:
      - postgres:postgres
    image: dpage/pgadmin4:6.20
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12121212

  redis:
    container_name: redis-cloud-saves
    image: redis:7.0.2
    ports:
      - "6379:6379"
    volumes:
      - ./docker-volumes/dev/redis:/data/redis

  minio:
    image: minio/minio:RELEASE.2024-03-15T01-07-19Z.fips
    volumes:
      - ./docker-volumes/dev/s3/data1-1:/data1
      - ./docker-volumes/dev/s3/data1-2:/data2
    ports:
      - "10000:9000"
      - "10001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio/data{1...2} --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
